Update github__pahealy7__apim-configuation__pr.yml for Azure Pipelines

diff --git a/github__pahealy7__apim-configuation__pr.yml b/github__pahealy7__apim-configuation__pr.yml
--- a/github__pahealy7__apim-configuation__pr.yml
+++ b/github__pahealy7__apim-configuation__pr.yml
@@ -34,6 +34,8 @@ variables:
     value: AzDO pipeline check - state.txt
   - name: System.debug
     value: true
+  - name: pipelineBuildURL
+    value: $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
 
 resources:
   # Incoming Webhook service connection
@@ -68,6 +70,46 @@ jobs:
         # persistCredentials allows us to use the PAT generated by AzDO to post
         # to the status API below.
 
+      # Post the initial pending status to GitHub and initialize the tokens for later
+      - script: |
+          set -euxo pipefail
+
+          # Create a temporary directory to put our status files in
+          statusPostOutputDirectory="$(mktemp -d)"
+          echo "##vso[task.setvariable variable=statusPostOutputDirectory]$statusPostOutputDirectory"
+
+          # Fetch the PAT from the git configuration.
+          GIT_REMOTE="$(git config --get remote.origin.url)"
+          GIT_AUTH="$(git config --get "http.${GIT_REMOTE}.extraheader")"
+          echo "##vso[task.setvariable variable=gitAuthToken;isSecret=true]$GIT_AUTH"
+         
+          echo "Status post to ${{ parameters.githubpr.pull_request.statuses_url }}:"
+          cat << EOF | tee "${statusPostOutputDirectory}/pendingPost.json"
+          {
+            "state": "pending",
+            "context": "$(checkContext)",
+            "description": "$(checkDescription)",
+            "target_url": "$(pipelineBuildURL)"
+          }
+          EOF
+
+          curl -H "Accept: application/vnd.github.v3+json" \
+            -H "Content-Type: application/json" \
+            -H "${GIT_AUTH}" \
+            -X POST \
+            '${{ parameters.githubpr.pull_request.statuses_url }}' \
+            --data @"${OUTPUT}/statusPost.json" \
+            | tee "${statusPostOutputDirectory}/pendingReply.json"
+
+          # Error out if the response from GitHub has .errors in it, indicating the
+          # API call didn't actually succeed.
+          jq -cre '.errors' <"${statusPostOutputDirectory}/pendingReply.json" >/dev/null && {
+            echo '##vso[task.issue type=error;]GitHub commit status post failed.'
+            echo '##vso[task.complete result=Failed;done=true;]'
+          }
+        condition: always()
+        displayName: Post pending status to PR commit
+
       # This script step switches the repository that's been checked out above
       # to the head of the pull request so that we have the code we need to check.
       # NOTE: this only applies in *this job*, so if you split this into multiple
@@ -84,6 +126,7 @@ jobs:
       - script: |
           set -euxo pipefail
           # IMPLEMENT YOUR CHECKOUT TASK(S) HERE
+          sleep 5
           # This example will fail in step 1 if the file "fail1" exists
           test -f fail1 && {
             echo '##vso[task.issue type=error;]Failed in checkout step 1.'
@@ -94,6 +137,7 @@ jobs:
       - script: |
           set -euxo pipefail
           # ANOTHER CHECKOUT TASK
+          sleep 5
           # This example will fail in step 1 if the file "fail2" exists
           test -f fail2 && {
             echo '##vso[task.issue type=error;]Failed in checkout step 2.'
@@ -103,7 +147,7 @@ jobs:
 
       # This sets the overall status variable to success if we get here.
       - script: |
-          echo '##vso[task.setvariable variable=pipelineStatus]successNOTREALLY'
+          echo '##vso[task.setvariable variable=pipelineStatus]success'
         displayName: Set pipeline status to success
 
       # This triggers to set failure state if any previous step failed.
@@ -117,39 +161,34 @@ jobs:
       - script: |
           set -euxo pipefail
 
-          # Create a temporary directory to put our status files in
-          OUTPUT="$(mktemp -d)"
-          echo "##vso[task.setvariable variable=statusPostOutputDirectory]$OUTPUT"
-
           echo "Status post to ${{ parameters.githubpr.pull_request.statuses_url }}:"
-          cat << EOF | tee "$OUTPUT/statusPost.json"
+          cat << EOF | tee "${statusPostOutputDirectory}/statusPost.json"
           {
             "state": "$(pipelineStatus)",
             "context": "$(checkContext)",
             "description": "$(checkDescription)",
-            "target_url": "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
+            "target_url": "$(pipelineBuildURL)"
           }
           EOF
 
-          # Fetch the PAT from the git configuration.
-          GIT_REMOTE="$(git config --get remote.origin.url)"
-          GIT_AUTH="$(git config --get "http.${GIT_REMOTE}.extraheader")"
           curl -H "Accept: application/vnd.github.v3+json" \
             -H "Content-Type: application/json" \
             -H "${GIT_AUTH}" \
             -X POST \
             '${{ parameters.githubpr.pull_request.statuses_url }}' \
             --data @"${OUTPUT}/statusPost.json" \
-            | tee "$OUTPUT/statusReply.json"
+            | tee "${statusPostOutputDirectory}/statusReply.json"
 
           # Error out if the response from GitHub has .errors in it, indicating the
           # API call didn't actually succeed.
-          jq -cre '.errors' <"$OUTPUT/statusReply.json" >/dev/null && {
+          jq -cre '.errors' <"${statusPostOutputDirectory}/statusReply.json" >/dev/null && {
             echo '##vso[task.issue type=error;]GitHub commit status post failed.'
             echo '##vso[task.complete result=Failed;done=true;]'
           }
+        env:
+          GIT_AUTH: $(gitAuthToken)
         condition: always()
-        displayName: Post commit status
+        displayName: Post completed status to PR commit
 
       # Publish what we posted to and received from GitHub into a pipeline artifact
       - task: PublishPipelineArtifact@1
